notifications:
  email:
    recipients:
      - pgroonga@ml.commit-email.info
dist: trusty
language: c
matrix:
  include:
    - env:
        PG_VERSION: 9.3
      addons:
        postgresql: "9.3"
    - env:
        PG_VERSION: 9.4
      addons:
        postgresql: "9.4"
    - env:
        PG_VERSION: 9.5
      addons:
        postgresql: "9.5"
    - env:
        PG_VERSION: 9.6
        WAL_SUPPORTED: "yes"
      addons:
        postgresql: "9.6"
    # - env:
    #     PG_VERSION: 10
    #     WAL_SUPPORTED: "yes"
    #   addons:
    #     postgresql: "10"
    - env:
        PG_VERSION: 9.6
        WAL_SUPPORTED: "yes"
        GROONGA_MASTER: "yes"
      addons:
        postgresql: "9.6"
sudo: required
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y postgresql-server-dev-${PG_VERSION} libmsgpack-dev
  - curl --silent --location https://github.com/groonga/groonga/raw/master/data/travis/setup.sh | sh
  - sudo apt-get install -qq -y groonga-token-filter-stem
  - |
    if [ "${WAL_SUPPORTED}" = "yes" ]; then
      rvm use 2.3.3 --install --binary --fuzzy
      gem install test-unit
    fi
before_script:
  - PKG_CONFIG_PATH=$PWD/data/travis/pkgconfig make DEBUG=1 HAVE_MSGPACK=1
  - sudo make install
script:
  - |
    case ${PG_VERSION} in
      9.3)
        for path in jsonb/ \
                    function/flush/jsonb.sql \
                    full-text-search/jsonb/ \
                    full-text-search/text/options/normalizer/ \
                    full-text-search/text/options/tokenizer/ \
                    reindex/analyze.sql \
                    regexp/text/options/ \
                    groonga-function/tuple-is-alive/ \
                    groonga-function/tuple-is-alive/ \
                    term-search/text/options/
        do
          rm -rf sql/${path}
        done
        rm -rf sql/compatibility
        ;;
      9.4)
        for path in full-text-search/text/options/normalizer/ \
                    full-text-search/text/options/tokenizer/ \
                    regexp/text/options/ \
                    term-search/text/options/
        do
          rm -rf sql/$path
          rm -rf sql/compatibility/schema/$path
        done
        ;;
    esac
  - |
    if [ "${WAL_SUPPORTED}" != "yes" ]; then
      rm -rf sql/function/wal-apply/
      rm -rf sql/function/wal-truncate/
      rm -rf sql/function/set-writable/
    fi
  # TODO: Remove me when Groonga 8.0.1 has been released.
  - rm -rf sql/function/score/ctid/
  - sudo -u postgres -H mkdir -p /tmp/space
  - |
    # (for i in $(seq 600)
    #  do
    #    sleep 1
    #    df -h | grep ramfs
    #  done) &
    PG_REGRESS_DIFF_OPTS="-u" \
      make installcheck \
        TMP_DIR=/tmp \
        SETUP_TMP_DIR=no \
        EXTRA_REGRESS_OPTS="--launcher=$(pwd)/test/short-pgappname"
  - |
    if [ "${WAL_SUPPORTED}" = "yes" ]; then
      test/run-test.rb
    fi
after_failure:
  - cat regression.diffs
#  - sudo cat /var/ramfs/postgresql/${PG_VERSION}/main/pgroonga.log
